endpoints:
  health:
    sensative: false

spring:
  session:
    storage-type: redis
    redis:
      namespace: spring:session
      flush-mode: on_save
      host: redis-cluster
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
  zipkin:
    base-url: http://zipkin:9411/
    
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
