endpoints:
  enabled: true
  jolokia:
    enabled: true
    sensative: false
  actuator:
    enabled: true
    sensative: false
  health:
    sensative: false

spring:
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
  zipkin:
    base-url: http://zipkin:9411/
    
management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
