endpoints:
  health:
    sensative: false

spring:
  redis:
    namespace: spring:session
    flush-mode: on_save
    cluster:
      nodes:
        - redis-cluster-0:6379
        - redis-cluster-1:6379
        - redis-cluster-2:6379
        - redis-cluster-3:6379
        - redis-cluster-4:6379
        - redis-cluster-5:6379
  session:
    storage-type: redis
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
  zipkin:
    base-url: http://zipkin:9411/
    
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
