endpoints:
  health:
    sensative: false

spring:
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
  zipkin:
    base-url: http://zipkin:9411/
    
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
